### ISSUE TITLE
This Plugin violates GPLv3 license

### ISSUE THREAD

**Issue by gutemine** [fairbird/BackUpFlash#17]
The swaproot Binaries shipped with the BackupFlash Plugin are violating the GPLv3 license, as they we're NOT authoritized by the author (=myself) for distribution by the owner of this GitHub account and the source Code ist Not in his property either.

**Comment by fairbird** [comment]
Thank you for info me ... I will remove swaproot file from here and upload it in other server .. After that I will edit plugin  to download it from new link after install plugin ...

**Comment by gutemine** [comment]
You are NOT getting what a License violation means. 
You have to STOP distributing MY binaries without permission IMMEDIATELY - NO matter from which server!

**Comment by fairbird** [comment]
what ?!! .. did you forget ?!! .... I already asked you since the first release of this plugin two years ago, if my memory does not betray me, I do not remember in any particular location, if I can just use your swaproot file and you did not object and said it is ok!!!

**Comment by gutemine** [comment]
Do NOT pretend that you have a permission when this is NOT true. Finally please READ the title of this issue - you are violating GPLv3 if you neither have the sources or the permission to distribute in binary form. Finally the author has the right to withdraw such rights at ANY time. The discussion is therefore OVER, you remove the binaries from ALL your Plugins and YOU and others don*t DISTRIBUTE them in ANY form or version without having proper(!) authorization of the author (=myeself)!

**Comment by fairbird** [comment]
1- I do not invent words from my imagination .. I actually asked you and you agreed ... and now you are not ...
2-I don't have a problem at all.. I will delete your swaproot file if that makes you happy.

Anyway, Thanks for strong memory
